from typing import Union

version: str
__version__: str
MODE_GENERIC: int
MODE_TEXT: int
MODE_FONT: int

class Compressor:
    def __init__(
        self, mode: int = ..., quality: int = ..., lgwin: int = ..., lgblock: int = ...
    ): ...
    def process(self, string): ...
    def flush(self): ...
    def finish(self, string):
        Union[bytes, bytearray] = ...

class Decompressor:
    def __init__(self): ...
    def process(self, string): ...
    def is_finished(self):
        bool = ...  # noqa: F841

def compress(
    string, mode: int = ..., quality: int = ..., lgwin: int = ..., lgblock: int = ...
): ...
def decompress(string): ...

class error(Exception): ...
